name: Main workflow
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run eslint
        working-directory: ./blog-api
        run: |
          npm install
          npx eslint .
