name: Main workflow
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run eslint
        uses: actions/checkout@v2
        working-directory: ./blog-api
        run: |
          npm install
          npx eslint .
